version: '3'
services:
  customerservice:
    build:
      context: src/customerservice
    ports:
      - 3002:3002
    environment:
      - DB_HOST=customerdb
    depends_on:
      - customerdb

  orderservice:
    build:
      context: src/orderservice
    ports:
      - 3003:3003
    environment:
      - DB_HOST=orderdb
    depends_on:
      - orderdb

  orderdb:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=microservices-test
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  customerdb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=microservices-test
      - MYSQL_ROOT_PASSWORD=my-secret-pw