version: '3'
services:
  customerservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=microservices-test
      - MYSQL_ROOT_PASSWORD=my-secret-pw